name: livrodereceitas
description: Uma aplicação de livro de receitas.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  connectivity: ^0.4.8+6
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true